CREATE TABLE `TRANSACTIONS` (
    `ref_num` VARCHAR(256) NOT NULL UNIQUE,
	`amount` FLOAT NOT NULL,
	`description` VARCHAR(256),
	`date` VARCHAR(256) NOT NULL,
	`entity` VARCHAR(256) NOT NULL,
    `category_id` INT,
	`budget_id` INT,
	`source_id` INT,
	`month_id` INT
);

CREATE TABLE `CATEGORIES` (
    `id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(256) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
);

CREATE TABLE `BUDGETS` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`category_id` INT NOT NULL,
	`month_id` INT NOT NULL,
	`distribution_id` INT NOT NULL,
    `amount` FLOAT NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `MONTHS` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(256) NOT NULL UNIQUE,
	PRIMARY KEY (`id`)
);

CREATE TABLE `SHORT_NAMES` (
	`long_name` VARCHAR(255) NOT NULL,
	`short_name` VARCHAR(256) NOT NULL,
    PRIMARY KEY (`long_name`)
);

CREATE TABLE `SOURCES` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(256) NOT NULL UNIQUE,
	`last_import` DATETIME NOT NULL,
	PRIMARY KEY (`id`)
);

ALTER TABLE `TRANSACTIONS` ADD CONSTRAINT `TRANSACTIONS_fk0` FOREIGN KEY (`category_id`) REFERENCES `CATEGORIES`(`id`);

ALTER TABLE `TRANSACTIONS` ADD CONSTRAINT `TRANSACTIONS_fk1` FOREIGN KEY (`budget_id`) REFERENCES `BUDGETS`(`id`);

ALTER TABLE `TRANSACTIONS` ADD CONSTRAINT `TRANSACTIONS_fk2` FOREIGN KEY (`source_id`) REFERENCES `SOURCES`(`id`);

ALTER TABLE `TRANSACTIONS` ADD CONSTRAINT `TRANSACTIONS_fk3` FOREIGN KEY (`month_id`) REFERENCES `MONTHS`(`id`);

ALTER TABLE `BUDGETS` ADD CONSTRAINT `BUDGETS_fk0` FOREIGN KEY (`category_id`) REFERENCES `CATEGORIES`(`id`);

ALTER TABLE `BUDGETS` ADD CONSTRAINT `BUDGETS_fk1` FOREIGN KEY (`month_id`) REFERENCES `MONTHS`(`id`);

ALTER TABLE `BUDGETS` ADD CONSTRAINT `BUDGETS_fk2` FOREIGN KEY (`distribution_id`) REFERENCES `CATEGORIES`(`id`);